version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "**/*"
    # NOTE: schedule is syntactically required by Dependabot for a version-updates entry.
    # Security updates ignore this schedule (they trigger on alerts). We keep a minimal schedule.
    schedule:
      interval: "weekly"
    labels:
      - "test"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    # Required schedule block (see note above)
    schedule:
      interval: "weekly"
    labels:
      - "test"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    # Required schedule block (see note above)
    schedule:
      interval: "weekly"
    labels:
      - "test"
    open-pull-requests-limit: 0
