# actions/checkout@v2をするだけのテスト用のワークフロー
name: Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: old node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: old go lang
        uses: actions/setup-go@v1
        with:
          go-version: "1.15"
      - name: old python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: old java
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: old ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: old php
        uses: shivammathur/setup-php@v1
        with:
          php-version: "7.4"
      - name: Run a one-line script
        run: echo "Hello, world!"
