# actions/checkout@v2をするだけのテスト用のワークフロー
name: Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: old node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: old go lang
        uses: actions/setup-go@v1
        with:
          go-version: "1.15"
      - name: Run a one-line script
        run: echo "Hello, world!"
