# actions/checkout@v2をするだけのテスト用のワークフロー
name: Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, world!"
